# Generated by Django 4.1.5 on 2023-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bnb', '0002_game_rename_wordid_word_word_id_word_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamelog',
            fields=[
                ('gamelog_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_mode',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='word_length',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
