# Generated by Django 4.1.5 on 2023-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bnb', '0003_gamelog_remove_game_id_remove_word_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='rough',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='display',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
