# Generated by Django 4.1.5 on 2023-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bnb', '0005_word_phonetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('score_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('word_length', models.IntegerField(default=4)),
                ('difficulty', models.CharField(max_length=20)),
                ('player_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='<Imagine your name here, now go play>', max_length=100)),
                ('num_of_turns', models.CharField(default='--', max_length=100)),
            ],
        ),
    ]
